### ISSUE TITLE
Update NFT mutation endpoint

### ISSUE THREAD

**Issue by echohtp** [holaplex/candy-machine-factory#14]
# Problem
NFT off-chain metadata needs to be updated

# Proposed Solution
Add new mutation endpoint that accepts

- encrypted wallet
- nft mint hash 
- URL to uploaded metadata OR metadata JSON to be uploaded

**Comment by wbarksdale** [comment]
> OR metadata JSON to be uploaded
@echohtp do you want this to be a file upload? or a `JSON` type input arg

**Comment by echohtp** [comment]
> > OR metadata JSON to be uploaded
> 
> @echohtp do you want this to be a file upload? or a `JSON` type input arg, or either?

Either or 👍🏽 

metaplex js supports partial fields for updating 

```
const { uri: newUri } = await metaplex
    .nfts()
    .uploadMetadata({
        ...nft.json,
        name: "My Updated Metadata Name",
        description: "My Updated Metadata Description",
    })
    .run();
```
